# Generated by Django 5.1.6 on 2025-05-10 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=50)),
                ('imported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
